services:
  logmap:
    container_name: logmap
    build:
      context: ./logmap
      dockerfile: logmap-dockerfile
    ports:
      - 22:22
    # networks:
    #   - logmap-network
    platform: linux/amd64
  alcomo:
    container_name: alcomo
    build: 
      context: ./alcomo
      dockerfile: Dockerfile
    ports:
      - 23:22
    platform: linux/amd64

  mariadb:
    container_name: mariadb
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data: