services:
  logmap:
    container_name: logmap
    build:
      context: ./logmap
      dockerfile: logmap-dockerfile
    ports:
      - 22:22
    # networks:
    #   - logmap-network
    platform: linux/amd64
  alcomo:
    container_name: alcomo
    build: 
      context: ./alcomo
      dockerfile: Dockerfile
    ports:
      - 23:22
    platform: linux/amd64